config/routes.rb
TimeTracker::Application.routes.draw do

  root :to => 'events#index'

  resources :categories, :only => [:index, :create, :update] do
    collection do
      get 'pie_data'
      get 'analyze'
      get 'titles'
    end
  end

  resources :events, :only => [:index, :create, :update] do
    collection do
      post 'create_multiple'
      get 'time_intervals'
    end
  end

  resources :settings, :only => [:index]

  resources :life_phases, :only => [:create]

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :events

  attr_accessible :parent_id, :id, :name

  def parent
    return Category.find(parent_id)
  end

  def children
    return Category.where("parent_id = ?", id)
  end

  def has_children?
    return !children.empty?
  end

  def total_time_spent(time_period = "Beginning of Time")
    events_array = events_for(time_period)
    time_spent = Event.sum_times_of(events_array)

    if has_children?
      children.each do |child|
        time_spent += child.total_time_spent(time_period)
      end
    end

    return time_spent
  end

  def events_for_last_30_days
    Event.events_for_month(self)
  end

  def events_for_last_7_days
    Event.events_for_week(self)
  end

  def events_for_last_6_months
    Event.events_for_6_months(self)
  end

  def events_for_last_year
    Event.events_for_6_months(self)
  end

  def full_bread_crumb_trail_html
    if parent_id == 0
      return bread_crumb_html
    else
      return parent.full_bread_crumb_trail_html + bread_crumb_html
    end
  end

  ##returns an array containing the ancestry of this category example: [great_grand_parent, grand_parent, parent]
  def ancestry
    if parent_id == 0
      return []
    else
      return [parent.ancestry, parent].flatten!
    end
  end

  def children_with_times(time_period)
    children_with_times = Array.new()
    children.each_with_index do |child|
      children_info = Hash.new()
      children_info[:label] = child.name
      children_info[:data] = child.total_time_spent(time_period)
      children_with_times << children_info
    end
    return children_with_times
  end

  def self.titles
    titles = []
    Category.uniq.pluck(:name).each do |category_title|
      titles << category_title
    end
    return titles
  end

  private

  def bread_crumb_html
    return '<li><a class="bread" href="#">' + title + '</a>&nbsp / &nbsp</li>'
  end

  def events_for(time_period)

    if time_period == "Month"
      puts "month"
      events_array = events_for_last_30_days
    elsif time_period == "Week"
      puts "week"

      events_array = events_for_last_7_days
    elsif time_period == "6 Months"
      puts "6months"

      events_array = events_for_last_6_months
    elsif time_period == "Year"
      puts "year"

      events_array = events_for_last_year
    else
      puts "beg of time"
      events_array = events
    end
    return events_array
  end
end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :category
  belongs_to :time_interval

  attr_accessible :time_interval_id, :category_id, :description, :created_at, :time_interval

  scope :events_for_month, ->(category_id) { where("created_at > ? AND category_id = ?", (Date.today - 1.month), category_id) }
  scope :events_for_6_months, ->(category_id) { where("created_at > ? AND category_id = ?", (Date.today - 6.months), category_id) }
  scope :events_for_week, ->(category_id) { where("created_at > ? AND category_id = ?", (Date.today - 7.days), category_id) }
  scope :events_for_year, ->(category_id) { where("created_at > ? AND category_id = ?", (Date.today - 12.months), category_id) }

  def self.sum_times_of(events)

    sum = 0
    events.each do |event|
      sum += TimeInterval.find(event.time_interval_id).to_hours
    end

    return sum
  end

end

app/models/life_phase.rb
class LifePhase < ActiveRecord::Base
  attr_accessible :name, :date
end

app/models/time_interval.rb
class TimeInterval < ActiveRecord::Base

  has_many :events

  attr_accessible :name, :id

  def interval
    return name
  end

  def to_hours
    case format
      when :hours_and_mins
        return hours_and_mins_format_to_hours
      when :mins
        return mins_format_to_hours
      when :hours
        return hours_format_to_hours
    end
  end

  private

  def format
    interval_array = self.interval.split(" ")
    if interval_array.length == 4 #format == "1 hr 30 mins"
      return :hours_and_mins
    elsif interval_array.length == 2
      if interval_array.last == "mins" #format == "30 mins"
        return :mins
      else #format == "2 hrs"
        return :hours
      end
    end
  end

  def hours_and_mins_format_to_hours
    array = interval.split(" ")
    hours = array[0].to_i
    mins = array[2].to_i

    return hours + TimeInterval.mins_to_hours(mins)
  end

  def mins_format_to_hours
    mins = interval.split(" ").first.to_i
    return TimeInterval.mins_to_hours(mins)
  end

  def hours_format_to_hours
    return interval.split(" ").first.to_i
  end

  def self.mins_to_hours(mins)
    return mins/60.0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.where("name like ?", "%#{params[:q]}%")
    respond_to do |format|
      format.html
      format.json {render :json => @categories }
    end
  end

  def analyze
  end

  def pie_data
    @category = Category.find_by_name(params[:category_name])
    time_period = params[:time_period]

    category_general_data = {
      :time => @category.total_time_spent(time_period),
      :ancestry_titles => @category.ancestry.map { |category| category.name}
    }

    full_data = Hash.new()
    full_data[:pie_data] = @category.children_with_times(time_period)
    full_data[:category_general_data] = category_general_data

    render json: full_data
  end

  def create
    @category = Category.create!(name: params[:category][:name], parent_id: params[:category][:parent_id])
    redirect_to(:back)
  end

  def titles
    titles = Category.titles
    render json: titles
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @time_of_last_logged_event = Event.last.created_at.strftime("%l:%M %p") unless !Event.last
    @category = Category.new
    @event = Event.new
  end

  def create
    time_interval = TimeInterval.find(params[:event][:time_interval_id])
    description = params[:event][:description]
    parents_ids = params[:event][:category_id].split(",")
    parents_ids.each do |parent_id|
      Event.create!(time_interval: time_interval, description: description, category_id: parent_id)
    end
    redirect_to(:back)
  end

  def time_intervals
    @time_intervals = TimeInterval.where("name like ?", "%#{params[:q]}%")
    respond_to do |format|
      format.html
      format.json {render :json => @time_intervals }
    end
  end

end

app/controllers/life_phases_controller.rb
class LifePhasesController < ApplicationController
  def create
    name = params[:life_phase][:name]
    year = params[:life_phase]["date(1i)"]
    month = params[:life_phase]["date(2i)"]
    day = params[:life_phase]["date(3i)"]

    date = [year, month, day].join("-")

    @life_phase = LifePhase.create(name: name, date: date)

    if @life_phase.save

    end
    redirect_to(:back)
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  def index
    @category = Category.new
    @last_event = Event.last
    puts "#########last#########"
    puts @last_event.inspect
    puts "#########last#########"

    @life_phase = LifePhase.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/analyze.html.erb
<% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
<% end %>

<div class="row-fluid">
    <div class="pie_chart span9">
        <ol class="breadcrumb"></ol>
        <div id="interactive"></div>
        <div class="btn-group time_period">
            <button type="button" class="btn time_button" id="Week">Week</button>
            <button type="button" class="btn time_button" id="Month">Month</button>
            <button type="button" class="btn time_button" id="6_Months">6 Months</button>
            <button type="button" class="btn time_button" id="year">Year</button>
            <button type="button" class="btn time_button" id="Beginning_of_time">Beginning of Time</button>
        </div>
    </div>
</div>

<div class="well time span12"></div>

app/views/events/index.html.erb
<% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
<% end %>

<div class="well add_elements span3">
  <div class="add_event span12">

    <p><%= @time_of_last_logged_event %></p>

    <fieldset>
      <h3>Add Event</h3>

      <%= form_for @event do |f| %>
          <p>
            <%= f.label :category_id, "Name" %>
            <%= f.text_field :category_id %>
          </p>
          <p>
            <%= f.label :time_interval_id, "Time Interval" %>
            <%= f.text_field :time_interval_id %>
          </p>

          <p>
            <%= label_tag(:description) %>
            <%= f.text_area :description %>
          </p>

          <p>
            <%= submit_tag("Create") %>
          </p>

      <% end %>

    </fieldset>
  </div>

  <div class="add_category span12">
    <fieldset>
      <h3>Add Category</h3>

      <%= form_for @category do |f| %>
          <p>
            <%= f.label :name %>
            <%= f.text_field :name %>
          </p>

          <p>
            <%= f.label :parent_id, "Parent" %>
            <%= f.text_field(:parent_id) %>
          </p>

          <p>
            <%= submit_tag("Create") %>
          </p>

      <% end %>
    </fieldset>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:name) ? yield(:name) : "TimeTracker" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="container-fluid nav-collapse">
            <ul class="nav navbar-nav span8">
              <li><a class="brand" href="#">TimeTracker</a></li>
              <li><a href="<%= root_path %>">Logger</a></li>
              <li><a href="<%= analyze_categories_path %>">Analytics</a></li>
            </ul>
            <ul class="nav navbar-nav span3">
              <li><a href="<%= settings_path %>">Settings</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
    </div><!--/row-->
  </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/settings/index.html.erb
<% unless !@last_event %>
    <div class="well edit_last_event span3">
        <fieldset>
          <h3>Edit Event</h3>

          <%= form_for @last_event do |f| %>

              <p>
                <%= f.label :category_id, "Name" %>
                <%= f.text_field :category_id %>
              </p>
              <p>
                <%= f.label :time_interval_id, "Time Interval" %>
                <%= f.text_field :time_interval_id %>
              </p>

              <p>
                <%= label_tag(:description) %>
                <%= f.text_area :description %>
              </p>

              <p>
                <%= submit_tag("Create") %>
              </p>

          <% end %>

        </fieldset>
    </div>
<% end %>

<div class="well create_life_phase span3">
  <fieldset>
    <h3>Create Life Phase</h3>

    <%= form_for @life_phase do |f| %>
        <p>
          <%= f.label :name %>
          <%= f.text_field :name %>
        </p>

        <p>
          <%= f.label :date %>
          <%= f.date_select :date %>
        </p>

        <p>
          <%= submit_tag("Create") %>
        </p>

    <% end %>
  </fieldset>
</div>